-- Esquema inicial. Refleja las entidades JPA tal como estaban antes de
-- introducir dispositivos.requiere_serie (ver V2).
--
-- Los nombres de columna siguen la estrategia por defecto de Spring Boot
-- (CamelCaseToUnderscoresNamingStrategy), salvo donde la entidad declara
-- un @Column(name = ...) explícito.
--
-- Los CHECK de los enums replican lo que Hibernate genera para
-- @Enumerated(EnumType.STRING). Si se añade un valor a un enum de Java,
-- hay que actualizar el CHECK en una migración nueva o fallarán los INSERT.

CREATE TABLE usuarios (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    username       VARCHAR(255) NOT NULL,
    contrasena     VARCHAR(255) NOT NULL,
    empresa        VARCHAR(255),
    rol            VARCHAR(255) NOT NULL,
    fecha_creacion TIMESTAMP(6),
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT ck_usuarios_empresa CHECK (empresa IN ('LYBTEL', 'RUNA')),
    CONSTRAINT ck_usuarios_rol CHECK (rol IN ('ADMIN', 'USER'))
);

CREATE TABLE locales (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(255) NOT NULL,
    empresa VARCHAR(255) NOT NULL,
    activo  BOOLEAN NOT NULL,
    CONSTRAINT uk_locales_nombre_empresa UNIQUE (nombre, empresa),
    CONSTRAINT ck_locales_empresa CHECK (empresa IN ('LYBTEL', 'RUNA'))
);

CREATE TABLE ubicaciones_fisicas (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(255) NOT NULL,
    local_id BIGINT NOT NULL,
    activo   BOOLEAN NOT NULL,
    CONSTRAINT fk_ubicaciones_local FOREIGN KEY (local_id) REFERENCES locales (id)
);

CREATE TABLE dispositivos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre            VARCHAR(255) NOT NULL,
    es_componente_cpu BOOLEAN NOT NULL,
    CONSTRAINT uk_dispositivos_nombre UNIQUE (nombre)
);

CREATE TABLE marcas (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    dispositivo_id BIGINT NOT NULL,
    CONSTRAINT fk_marcas_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivos (id),
    CONSTRAINT uk_marcas_nombre_dispositivo UNIQUE (nombre, dispositivo_id)
);

CREATE TABLE estaciones (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa             VARCHAR(255) NOT NULL,
    nombre              VARCHAR(255) NOT NULL,
    local_id            BIGINT NOT NULL,
    ubicacion_fisica_id BIGINT NOT NULL,
    numero              INTEGER NOT NULL,
    activo              BOOLEAN NOT NULL,
    fecha_creacion      TIMESTAMP(6),
    CONSTRAINT fk_estaciones_local FOREIGN KEY (local_id) REFERENCES locales (id),
    CONSTRAINT fk_estaciones_ubicacion FOREIGN KEY (ubicacion_fisica_id) REFERENCES ubicaciones_fisicas (id),
    CONSTRAINT uk_estaciones_local_ubicacion_numero UNIQUE (local_id, ubicacion_fisica_id, numero),
    CONSTRAINT ck_estaciones_empresa CHECK (empresa IN ('LYBTEL', 'RUNA'))
);

CREATE TABLE inventario_fisico (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa        VARCHAR(255) NOT NULL,
    estacion_id    BIGINT,
    parent_id      BIGINT,
    dispositivo_id BIGINT NOT NULL,
    marca_id       BIGINT NOT NULL,
    modelo         VARCHAR(255),
    serie          VARCHAR(255),
    ram_tipo       VARCHAR(255),
    ram_espacio    INTEGER,
    procesador     VARCHAR(255),
    pulgadas       INTEGER,
    disco_tipo     VARCHAR(255),
    disco_espacio  INTEGER,
    hostname       VARCHAR(255),
    CONSTRAINT fk_fisico_estacion FOREIGN KEY (estacion_id) REFERENCES estaciones (id),
    CONSTRAINT fk_fisico_parent FOREIGN KEY (parent_id) REFERENCES inventario_fisico (id),
    CONSTRAINT fk_fisico_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivos (id),
    CONSTRAINT fk_fisico_marca FOREIGN KEY (marca_id) REFERENCES marcas (id),
    CONSTRAINT ck_fisico_empresa CHECK (empresa IN ('LYBTEL', 'RUNA')),
    CONSTRAINT ck_fisico_ram_tipo CHECK (ram_tipo IN ('DDR3', 'DDR4', 'DDR5')),
    CONSTRAINT ck_fisico_disco_tipo CHECK (disco_tipo IN ('SSD', 'HDD', 'M2'))
);

-- contrasena guarda el cifrado AES-GCM en base64 (SecretEncryptionConverter);
-- la entidad lo declara con @Column(length = 512).
CREATE TABLE inventario_logico (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa       VARCHAR(255) NOT NULL,
    estacion_id   BIGINT,
    tipo_acceso   VARCHAR(255) NOT NULL,
    identificador VARCHAR(255) NOT NULL,
    contrasena    VARCHAR(512),
    CONSTRAINT fk_logico_estacion FOREIGN KEY (estacion_id) REFERENCES estaciones (id),
    CONSTRAINT ck_logico_empresa CHECK (empresa IN ('LYBTEL', 'RUNA')),
    CONSTRAINT ck_logico_tipo_acceso CHECK (tipo_acceso IN (
        'DISCORD', 'GOOGLE', 'USUARIOR', 'WINFORCE', 'SICACENTER', 'ISSABEL', 'WHATSAPP', 'ALBRU'
    ))
);

-- PostgreSQL no indexa las claves foráneas automáticamente y sin índice
-- cada borrado del lado padre provoca un scan secuencial en la tabla hija.
CREATE INDEX idx_ubicaciones_local ON ubicaciones_fisicas (local_id);
CREATE INDEX idx_marcas_dispositivo ON marcas (dispositivo_id);
CREATE INDEX idx_estaciones_local ON estaciones (local_id);
CREATE INDEX idx_estaciones_ubicacion ON estaciones (ubicacion_fisica_id);
CREATE INDEX idx_fisico_estacion ON inventario_fisico (estacion_id);
CREATE INDEX idx_fisico_parent ON inventario_fisico (parent_id);
CREATE INDEX idx_fisico_dispositivo ON inventario_fisico (dispositivo_id);
CREATE INDEX idx_fisico_marca ON inventario_fisico (marca_id);
CREATE INDEX idx_logico_estacion ON inventario_logico (estacion_id);
